### PR TITLE
Pytest assume summary hook

### PR DESCRIPTION
**Pull request by ptrivedi2610**

### CODE REVIEW

**Comment by ptrivedi2610** [comment]
@astraw38 
That was invalid testing from my end. I have completed all the changes and have added tests from my end.
*Please review and merge*

**Comment by ptrivedi2610** [comment]
@astraw38 
I request if you can change the revision, or can point me to change it.

**Comment by ptrivedi2610** [comment]
@astraw38 Any updates ? Is this good to merge ?

**Comment by ptrivedi2610** [comment]
@astraw38 Do we need to change the version ? Also, we need to publish this on PyPi. Can you please help me with the same

**Comment by astraw38** [comment]
I've already been working on it.

**Pull request merged**
